/*Copyright (c) 2016-2017 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.guardian.dublinauth.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.guardian.dublinauth.Role;
import com.guardian.dublinauth.UserRoleMapping;


/**
 * ServiceImpl object for domain model class Role.
 *
 * @see Role
 */
@Service("DublinAuth.RoleService")
public class RoleServiceImpl implements RoleService {

    private static final Logger LOGGER = LoggerFactory.getLogger(RoleServiceImpl.class);

    @Autowired
	@Qualifier("DublinAuth.UserRoleMappingService")
	private UserRoleMappingService userRoleMappingService;

    @Autowired
    @Qualifier("DublinAuth.RoleDao")
    private WMGenericDao<Role, String> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Role, String> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "DublinAuthTransactionManager")
    @Override
	public Role create(Role role) {
        LOGGER.debug("Creating a new Role with information: {}", role);
        Role roleCreated = this.wmGenericDao.create(role);
        if(roleCreated.getUserRoleMappings() != null) {
            for(UserRoleMapping userRoleMapping : roleCreated.getUserRoleMappings()) {
                userRoleMapping.setRole(roleCreated);
                LOGGER.debug("Creating a new child UserRoleMapping with information: {}", userRoleMapping);
                userRoleMappingService.create(userRoleMapping);
            }
        }
        return roleCreated;
    }

	@Transactional(readOnly = true, value = "DublinAuthTransactionManager")
	@Override
	public Role getById(String roleIdInstance) throws EntityNotFoundException {
        LOGGER.debug("Finding Role by id: {}", roleIdInstance);
        Role role = this.wmGenericDao.findById(roleIdInstance);
        if (role == null){
            LOGGER.debug("No Role found with id: {}", roleIdInstance);
            throw new EntityNotFoundException(String.valueOf(roleIdInstance));
        }
        return role;
    }

    @Transactional(readOnly = true, value = "DublinAuthTransactionManager")
	@Override
	public Role findById(String roleIdInstance) {
        LOGGER.debug("Finding Role by id: {}", roleIdInstance);
        return this.wmGenericDao.findById(roleIdInstance);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "DublinAuthTransactionManager")
	@Override
	public Role update(Role role) throws EntityNotFoundException {
        LOGGER.debug("Updating Role with information: {}", role);
        this.wmGenericDao.update(role);

        String roleIdInstance = role.getRoleId();

        return this.wmGenericDao.findById(roleIdInstance);
    }

    @Transactional(value = "DublinAuthTransactionManager")
	@Override
	public Role delete(String roleIdInstance) throws EntityNotFoundException {
        LOGGER.debug("Deleting Role with id: {}", roleIdInstance);
        Role deleted = this.wmGenericDao.findById(roleIdInstance);
        if (deleted == null) {
            LOGGER.debug("No Role found with id: {}", roleIdInstance);
            throw new EntityNotFoundException(String.valueOf(roleIdInstance));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "DublinAuthTransactionManager")
	@Override
	public Page<Role> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Roles");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "DublinAuthTransactionManager")
    @Override
    public Page<Role> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Roles");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "DublinAuthTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service DublinAuth for table Role to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "DublinAuthTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "DublinAuthTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "DublinAuthTransactionManager")
    @Override
    public Page<UserRoleMapping> findAssociatedUserRoleMappings(String roleId, Pageable pageable) {
        LOGGER.debug("Fetching all associated userRoleMappings");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("role.roleId = '" + roleId + "'");

        return userRoleMappingService.findAll(queryBuilder.toString(), pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service UserRoleMappingService instance
	 */
	protected void setUserRoleMappingService(UserRoleMappingService service) {
        this.userRoleMappingService = service;
    }

}

